<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__vfb-5</name>
   <tag></tag>
   <elementGuidId>11d8b8e1-1a23-4883-b85d-27d3dfe1c62d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vfb-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78d7a148-f9e3-4870-8cd1-6f51d2c5da96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5077c609-407b-44eb-b56b-127c1862ff3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-5</value>
      <webElementGuid>213bc5cc-9933-4cf0-8cae-c8f9d67e7540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-5</value>
      <webElementGuid>cf4d3ce3-f17b-488d-9d55-c8d029324246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text  vfb-medium  required  </value>
      <webElementGuid>590ea371-edb1-4d16-a2a7-71371d535fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-5&quot;)</value>
      <webElementGuid>f5b9b6b2-7777-40c3-b623-8f70356588f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-5']</value>
      <webElementGuid>b564fefb-742a-488f-ba27-db19eb21ae6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-5']/input</value>
      <webElementGuid>6b2e6862-2ec9-4634-bd88-6b367f86695c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>8b85443e-875f-4fd8-b4a0-21e05e6f6878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-5' and @id = 'vfb-5']</value>
      <webElementGuid>1351d25c-164f-49d4-9f0a-778b1525a0db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
