<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Andorra</name>
   <tag></tag>
   <elementGuidId>bfa86ec3-9748-46af-bda5-137d30d460e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-vfb-13-country-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-vfb-13-country-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>db5384d6-0035-443a-919d-dbc32549e957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>b5d11701-c47f-45b2-ab37-8b1bc30670ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-vfb-13-country-container</value>
      <webElementGuid>fae83f69-8bd6-4cab-ba92-9e8e36e3065d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>d76ba6c7-8892-49d8-9ca6-8ab317ea94bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>26e70d97-3fd4-471f-8793-4e4524defc78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Andorra</value>
      <webElementGuid>97370149-5704-4587-943b-621adebdac19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Andorra</value>
      <webElementGuid>ec4f15cc-17b8-43c3-9802-efee9185b4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-vfb-13-country-container&quot;)</value>
      <webElementGuid>bb95bfa8-21a0-495e-8ca1-e89ae1b90f62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-vfb-13-country-container']</value>
      <webElementGuid>d994fdf1-e40d-47f1-8116-d3ab174761b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-13']/div/span[6]/span/span/span/span</value>
      <webElementGuid>6d70d96a-5aa0-4a7d-95f3-034aa6500c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal / Zip Code'])[1]/following::span[5]</value>
      <webElementGuid>261313ab-c9b5-4034-a8e3-dc64b7da3d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State / Province / Region'])[1]/following::span[6]</value>
      <webElementGuid>159fdcb7-8a99-4d6a-b829-e40957050114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/preceding::span[3]</value>
      <webElementGuid>07c95e69-dd7d-47d8-891e-643e1e87cc65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[6]/span/span/span/span</value>
      <webElementGuid>a217375d-0dce-434b-8ae2-cd1bd35bd2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-vfb-13-country-container' and @title = 'Andorra' and (text() = 'Andorra' or . = 'Andorra')]</value>
      <webElementGuid>d1f6e935-ab01-4a30-8476-ec9b3b71d219</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
